### ISSUE TITLE
crashes and freezes FireTV Stick - Then creates a Memory Critically Low probelem 

### ISSUE THREAD

**Issue by joegiannini3** [Diblo/KODI-Popcorn-Time#10]
i installed it and ran on two separate FireTV sticks to see if the issue occurred more than once.

after running Kodi Popcorn Time the movie will start then a few minutes into any HD movie the movie will freeze or stop completely to the point of unplugging and repulsion just to get the Amazon Firetv stick to respond again. once rebooted a "Memory critically low" error pops up and asks to delete apps to continue using. trying not to lose the Kodi app i have uninstalled Kodi Popcorn time and also cleared cache but the problem still remains. Storage Data for Kodi now is:  Application 59.77mb & Data 4.04 GB Cache 77.68

**Comment by Diblo** [comment]
Hello
Thanks for you for reporting your bug.
The problem is that your box froze and therefore could torrent2http not remove the pre-allocate file.
It may help you to read this to solve the problem:
[Does it downloads the whole file? Do I need the space? Is it ever deleted?](https://github.com/Diblo/KODI-Popcorn-Time#does-it-downloads-the-whole-file-do-i-need-the-space-is-it-ever-deleted)
[Where is the file located? Can I change it?](https://github.com/Diblo/KODI-Popcorn-Time#where-is-the-file-located-can-i-change-it)
http://kodi.wiki/view/Userdata (Replace `userdata` with `addons`)
If you can not find the plugin folder and remove the file, I will come up with a patch to the problem.

**Comment by iAYMANi** [comment]
Is there a solution to the problem

**Comment by Diblo** [comment]
Solution add with commit: https://github.com/Diblo/KODI-Popcorn-Time/commit/7649f811e68fc436f4b050237a2752755e264c13
